name: CMake on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: install dependencies
      run: sudo apt install libbsd-dev uuid-dev libblocksruntime-dev libgtest-dev libssl-dev
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build newfs_hfs
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target newfs_hfs

    - name: Build fsck_hfs
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target fsck_hfs

    #- name: Test
    #  working-directory: ${{github.workspace}}/build
    #  run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target hfs-tests && ctest -C ${{env.BUILD_TYPE}}

